[package]
name = "aerugo-client"
version = "0.1.0"
edition = "2021"

[dependencies]
calloop = { workspace = true }
sctk = { workspace = true }
wayland-backend = { workspace = true }
zbus = { workspace = true }
