[workspace]
members = [
	"compositor/aerugo",
	"compositor/aerugo-framework",
	"compositor/aerugo-kms",
	"compositor/aerugo-windowed",

	"client",

	"app/launch",
]

# Enable LTO during release to make the binaries a bit smaller
[profile.release]
lto = true
opt-level = 3
strip = true
