[workspace]
members = [
	"aerugo-comp",
	"aerugo-comp/framework",
	"aerugo-comp/kms",
	"aerugo-comp/windowed",
]

# Enable LTO during release to make the binaries a bit smaller
[profile.release]
lto = true
opt-level = 'z'
strip = true
