[package]
name = "aerugo-launch"
version = "0.1.0"
edition = "2021"

[dependencies]
aerugo-client = { workspace = true }
cosmic-text = { workspace = true }
evalexpr = { workspace = true }
lyon = { workspace = true }
wasmtime = { workspace = true }
wgpu = { workspace = true }
