[package]
name = "aerugo-framework"
version = "0.1.0"
edition = "2021"

[dependencies.smithay]
git = "https://github.com/Smithay/smithay"
default-features = false
features = [
    "wayland_frontend"
]
